name: "go.micro.service.pod"
service_Host: "127.0.0.1"
service_Port: "8091"
version: "latest"

consul:
  host: "127.0.0.1"
  port: 8500
  prefix: "/micro/config"
  path: "mysql"

tracer:
  host: "127.0.0.1"
  port: 6832

prometheus:
  port: 9091