version: '3'
services:
  go-paas-volume:
    image: go-paas-volume:0.1
    container_name: go-paas-volume
    volumes:
      - /root/.kube/config:/.kube/config
    ports:
      - "8087:8087"
    depends_on:
      - mysql
      - consul

  go-paas-volumeApi:
    image: go-paas-volumeapi:0.1
    container_name: go-paas-volumeApi
    ports:
      - "8088:8088"
    depends_on:
      - mysql
      - consul

  go-paas-svc:
    image: go-paas-svc:0.1
    container_name: go-paas-svc
    volumes:
      - /root/.kube/config:/.kube/config
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - consul

  go-paas-svcApi:
    image: go-paas-svcapi:0.1
    container_name: go-paas-svcApi
    ports:
      - "8084:8084"
    depends_on:
      - mysql
      - consul

  go-paas-route:
    image: go-paas-route:0.1
    container_name: go-paas-route
    volumes:
      - /root/.kube/config:/.kube/config
    ports:
      - "8085:8085"
    depends_on:
      - mysql
      - consul

  go-paas-routeApi:
    image: go-paas-routeapi:0.1
    container_name: go-paas-routeApi
    ports:
      - "8086:8086"
    depends_on:
      - mysql
      - consul

  go-paas-middleware:
    image: go-paas-middleware:0.1
    container_name: go-paas-middleware
    volumes:
      - /root/.kube/config:/.kube/config
    ports:
      - "8089:8089"
    depends_on:
      - mysql
      - consul

  go-paas-middlewareApi:
    image: go-paas-middlewareapi:0.1
    container_name: go-paas-middlewareApi
    ports:
      - "8090:8090"
    depends_on:
      - mysql
      - consul

  go-paas-appStore:
    image: go-paas-appstore:0.1
    container_name: go-paas-appStore
    volumes:
      - /root/.kube/config.yaml:/root/.kube/config
    ports:
      - "8091:8091"
    depends_on:
      - mysql
      - consul

  go-paas-appStoreApi:
    image: go-paas-appstoreapi:0.1
    container_name: go-paas-appstoreApi
    ports:
      - "8092:8092"
    depends_on:
      - mysql
      - consul

  go-paas-pod:
    image: go-paas-pod:0.1
    container_name: go-paas-pod
    volumes:
      - /root/.kube/config:/.kube/config
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - consul

  go-paas-podApi:
    image: go-paas-podapi:0.1
    container_name: go-paas-podApi
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - consul

  go-paas-user:
    image: go-paas-user:0.1
    container_name: go-paas-user
    ports:
      - "8093:8093"
    depends_on:
      - mysql
      - consul

  go-paas-userApi:
    image: go-paas-userapi:0.1
    container_name: go-paas-userApi
    ports:
      - "8094:8094"
    depends_on:
      - mysql
      - consul

  mysql:
    image: mysql:5.7
    container_name: mysql57
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_DATABASE: "db3"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    
  consul:
    image: consul
    container_name: consul
    ports:
      - "8500:8500"

  gateway:
    image: cap1573/cap-api-gateway
    container_name: gateway
    command: api --handler=api
    ports:
      - "8080:8080"
    environment:
      - registry=consul
      - registry_address=192.168.147.138:8500
    depends_on:
      - consul
  

