FROM golang:alpine AS demoRouteApi
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

WORKDIR /go-paas/routeApi

COPY go.mod .
COPY go.sum .
ENV GOPROXY https://goproxy.cn
RUN go mod download

COPY . .

RUN go build -o go-paas-routeApi

FROM scratch

COPY ./conf /conf

COPY --from=demoRouteApi /go-paas/routeApi/go-paas-routeApi /

EXPOSE 8086

ENTRYPOINT ["/go-paas-routeApi", "conf/config.yaml"]