FROM golang:alpine AS demoSvcApi
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

WORKDIR /go-paas/svcApi

COPY go.mod .
COPY go.sum .
ENV GOPROXY https://goproxy.cn
RUN go mod download

COPY . .

RUN go build -o go-paas-svcApi

FROM scratch

COPY ./conf /conf

COPY --from=demoSvcApi /go-paas/svcApi/go-paas-svcApi /

EXPOSE 8084
ENTRYPOINT ["/go-paas-svcApi", "conf/config.yaml"]