// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.7
// source: proto/appStore/appStore.proto

package appStore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RAppInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AppInstall    int64        `protobuf:"varint,2,opt,name=app_install,json=appInstall,proto3" json:"app_install,omitempty"`
	AppViews      int64        `protobuf:"varint,3,opt,name=app_views,json=appViews,proto3" json:"app_views,omitempty"`
	AppCategoryId int64        `protobuf:"varint,4,opt,name=app_category_id,json=appCategoryId,proto3" json:"app_category_id,omitempty"`
	AppIsvId      int64        `protobuf:"varint,5,opt,name=app_isv_id,json=appIsvId,proto3" json:"app_isv_id,omitempty"`
	AppPrice      float32      `protobuf:"fixed32,6,opt,name=app_price,json=appPrice,proto3" json:"app_price,omitempty"`
	AppCheck      bool         `protobuf:"varint,7,opt,name=app_check,json=appCheck,proto3" json:"app_check,omitempty"`
	AppSku        string       `protobuf:"bytes,8,opt,name=app_sku,json=appSku,proto3" json:"app_sku,omitempty"`
	AppTitle      string       `protobuf:"bytes,9,opt,name=app_title,json=appTitle,proto3" json:"app_title,omitempty"`
	AppDetail     string       `protobuf:"bytes,10,opt,name=app_detail,json=appDetail,proto3" json:"app_detail,omitempty"`
	AppPod        []*AppPod    `protobuf:"bytes,11,rep,name=app_pod,json=appPod,proto3" json:"app_pod,omitempty"`
	AppMiddle     []*AppMiddle `protobuf:"bytes,12,rep,name=app_middle,json=appMiddle,proto3" json:"app_middle,omitempty"`
	AppVolume     []*AppVolume `protobuf:"bytes,13,rep,name=app_volume,json=appVolume,proto3" json:"app_volume,omitempty"`
}

func (x *RAppInfo) Reset() {
	*x = RAppInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_appStore_appStore_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RAppInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAppInfo) ProtoMessage() {}

func (x *RAppInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appStore_appStore_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAppInfo.ProtoReflect.Descriptor instead.
func (*RAppInfo) Descriptor() ([]byte, []int) {
	return file_proto_appStore_appStore_proto_rawDescGZIP(), []int{0}
}

func (x *RAppInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RAppInfo) GetAppInstall() int64 {
	if x != nil {
		return x.AppInstall
	}
	return 0
}

func (x *RAppInfo) GetAppViews() int64 {
	if x != nil {
		return x.AppViews
	}
	return 0
}

func (x *RAppInfo) GetAppCategoryId() int64 {
	if x != nil {
		return x.AppCategoryId
	}
	return 0
}

func (x *RAppInfo) GetAppIsvId() int64 {
	if x != nil {
		return x.AppIsvId
	}
	return 0
}

func (x *RAppInfo) GetAppPrice() float32 {
	if x != nil {
		return x.AppPrice
	}
	return 0
}

func (x *RAppInfo) GetAppCheck() bool {
	if x != nil {
		return x.AppCheck
	}
	return false
}

func (x *RAppInfo) GetAppSku() string {
	if x != nil {
		return x.AppSku
	}
	return ""
}

func (x *RAppInfo) GetAppTitle() string {
	if x != nil {
		return x.AppTitle
	}
	return ""
}

func (x *RAppInfo) GetAppDetail() string {
	if x != nil {
		return x.AppDetail
	}
	return ""
}

func (x *RAppInfo) GetAppPod() []*AppPod {
	if x != nil {
		return x.AppPod
	}
	return nil
}

func (x *RAppInfo) GetAppMiddle() []*AppMiddle {
	if x != nil {
		return x.AppMiddle
	}
	return nil
}

func (x *RAppInfo) GetAppVolume() []*AppVolume {
	if x != nil {
		return x.AppVolume
	}
	return nil
}

type RequestID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RequestID) Reset() {
	*x = RequestID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_appStore_appStore_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestID) ProtoMessage() {}

func (x *RequestID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appStore_appStore_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestID.ProtoReflect.Descriptor instead.
func (*RequestID) Descriptor() ([]byte, []int) {
	return file_proto_appStore_appStore_proto_rawDescGZIP(), []int{1}
}

func (x *RequestID) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RequestCommentID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RequestCommentID) Reset() {
	*x = RequestCommentID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_appStore_appStore_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestCommentID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCommentID) ProtoMessage() {}

func (x *RequestCommentID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appStore_appStore_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCommentID.ProtoReflect.Descriptor instead.
func (*RequestCommentID) Descriptor() ([]byte, []int) {
	return file_proto_appStore_appStore_proto_rawDescGZIP(), []int{2}
}

func (x *RequestCommentID) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ResponseAllApp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppInfo []*RAppInfo `protobuf:"bytes,1,rep,name=app_info,json=appInfo,proto3" json:"app_info,omitempty"`
}

func (x *ResponseAllApp) Reset() {
	*x = ResponseAllApp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_appStore_appStore_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseAllApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseAllApp) ProtoMessage() {}

func (x *ResponseAllApp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appStore_appStore_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseAllApp.ProtoReflect.Descriptor instead.
func (*ResponseAllApp) Descriptor() ([]byte, []int) {
	return file_proto_appStore_appStore_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseAllApp) GetAppInfo() []*RAppInfo {
	if x != nil {
		return x.AppInfo
	}
	return nil
}

type RequestAllApp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RequestAllApp) Reset() {
	*x = RequestAllApp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_appStore_appStore_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestAllApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAllApp) ProtoMessage() {}

func (x *RequestAllApp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appStore_appStore_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAllApp.ProtoReflect.Descriptor instead.
func (*RequestAllApp) Descriptor() ([]byte, []int) {
	return file_proto_appStore_appStore_proto_rawDescGZIP(), []int{4}
}

type ResponseNum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int64 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *ResponseNum) Reset() {
	*x = ResponseNum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_appStore_appStore_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseNum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseNum) ProtoMessage() {}

func (x *ResponseNum) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appStore_appStore_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseNum.ProtoReflect.Descriptor instead.
func (*ResponseNum) Descriptor() ([]byte, []int) {
	return file_proto_appStore_appStore_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseNum) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type AppPod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId    int64 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppPodId int64 `protobuf:"varint,2,opt,name=app_pod_id,json=appPodId,proto3" json:"app_pod_id,omitempty"`
}

func (x *AppPod) Reset() {
	*x = AppPod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_appStore_appStore_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppPod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppPod) ProtoMessage() {}

func (x *AppPod) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appStore_appStore_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppPod.ProtoReflect.Descriptor instead.
func (*AppPod) Descriptor() ([]byte, []int) {
	return file_proto_appStore_appStore_proto_rawDescGZIP(), []int{6}
}

func (x *AppPod) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *AppPod) GetAppPodId() int64 {
	if x != nil {
		return x.AppPodId
	}
	return 0
}

type AppMiddle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId       int64 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppMiddleId int64 `protobuf:"varint,2,opt,name=app_middle_id,json=appMiddleId,proto3" json:"app_middle_id,omitempty"`
}

func (x *AppMiddle) Reset() {
	*x = AppMiddle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_appStore_appStore_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppMiddle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppMiddle) ProtoMessage() {}

func (x *AppMiddle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appStore_appStore_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppMiddle.ProtoReflect.Descriptor instead.
func (*AppMiddle) Descriptor() ([]byte, []int) {
	return file_proto_appStore_appStore_proto_rawDescGZIP(), []int{7}
}

func (x *AppMiddle) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *AppMiddle) GetAppMiddleId() int64 {
	if x != nil {
		return x.AppMiddleId
	}
	return 0
}

type AppVolume struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId       int64 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppVolumeId int64 `protobuf:"varint,2,opt,name=app_volume_id,json=appVolumeId,proto3" json:"app_volume_id,omitempty"`
}

func (x *AppVolume) Reset() {
	*x = AppVolume{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_appStore_appStore_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppVolume) ProtoMessage() {}

func (x *AppVolume) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appStore_appStore_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppVolume.ProtoReflect.Descriptor instead.
func (*AppVolume) Descriptor() ([]byte, []int) {
	return file_proto_appStore_appStore_proto_rawDescGZIP(), []int{8}
}

func (x *AppVolume) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *AppVolume) GetAppVolumeId() int64 {
	if x != nil {
		return x.AppVolumeId
	}
	return 0
}

type RAppComment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId            int64  `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppUserId        int64  `protobuf:"varint,2,opt,name=app_user_id,json=appUserId,proto3" json:"app_user_id,omitempty"`
	AppCommentTitle  string `protobuf:"bytes,3,opt,name=app_comment_title,json=appCommentTitle,proto3" json:"app_comment_title,omitempty"`
	AppCommentDetail string `protobuf:"bytes,4,opt,name=app_comment_detail,json=appCommentDetail,proto3" json:"app_comment_detail,omitempty"`
}

func (x *RAppComment) Reset() {
	*x = RAppComment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_appStore_appStore_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RAppComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAppComment) ProtoMessage() {}

func (x *RAppComment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appStore_appStore_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAppComment.ProtoReflect.Descriptor instead.
func (*RAppComment) Descriptor() ([]byte, []int) {
	return file_proto_appStore_appStore_proto_rawDescGZIP(), []int{9}
}

func (x *RAppComment) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *RAppComment) GetAppUserId() int64 {
	if x != nil {
		return x.AppUserId
	}
	return 0
}

func (x *RAppComment) GetAppCommentTitle() string {
	if x != nil {
		return x.AppCommentTitle
	}
	return ""
}

func (x *RAppComment) GetAppCommentDetail() string {
	if x != nil {
		return x.AppCommentDetail
	}
	return ""
}

type ResponseAllAppComment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppComment []*RAppComment `protobuf:"bytes,1,rep,name=app_comment,json=appComment,proto3" json:"app_comment,omitempty"`
}

func (x *ResponseAllAppComment) Reset() {
	*x = ResponseAllAppComment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_appStore_appStore_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseAllAppComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseAllAppComment) ProtoMessage() {}

func (x *ResponseAllAppComment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appStore_appStore_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseAllAppComment.ProtoReflect.Descriptor instead.
func (*ResponseAllAppComment) Descriptor() ([]byte, []int) {
	return file_proto_appStore_appStore_proto_rawDescGZIP(), []int{10}
}

func (x *ResponseAllAppComment) GetAppComment() []*RAppComment {
	if x != nil {
		return x.AppComment
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_appStore_appStore_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appStore_appStore_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_appStore_appStore_proto_rawDescGZIP(), []int{11}
}

func (x *Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_proto_appStore_appStore_proto protoreflect.FileDescriptor

var file_proto_appStore_appStore_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x2f, 0x61, 0x70, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x61, 0x70, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x22, 0xc0, 0x03, 0x0a, 0x08, 0x52, 0x41,
	0x70, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x61, 0x70, 0x70,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x70, 0x70, 0x5f, 0x76,
	0x69, 0x65, 0x77, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x61, 0x70, 0x70, 0x56,
	0x69, 0x65, 0x77, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x61,
	0x70, 0x70, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x0a,
	0x61, 0x70, 0x70, 0x5f, 0x69, 0x73, 0x76, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x61, 0x70, 0x70, 0x49, 0x73, 0x76, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x70,
	0x70, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x61,
	0x70, 0x70, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x70, 0x70, 0x5f, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x70, 0x70, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x5f, 0x73, 0x6b, 0x75, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x70, 0x53, 0x6b, 0x75, 0x12, 0x1b, 0x0a,
	0x09, 0x61, 0x70, 0x70, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x61, 0x70, 0x70, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x70,
	0x70, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x61, 0x70, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x29, 0x0a, 0x07, 0x61, 0x70, 0x70,
	0x5f, 0x70, 0x6f, 0x64, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x70,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x41, 0x70, 0x70, 0x50, 0x6f, 0x64, 0x52, 0x06, 0x61, 0x70,
	0x70, 0x50, 0x6f, 0x64, 0x12, 0x32, 0x0a, 0x0a, 0x61, 0x70, 0x70, 0x5f, 0x6d, 0x69, 0x64, 0x64,
	0x6c, 0x65, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x70, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x2e, 0x41, 0x70, 0x70, 0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x52, 0x09, 0x61,
	0x70, 0x70, 0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x12, 0x32, 0x0a, 0x0a, 0x61, 0x70, 0x70, 0x5f,
	0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61,
	0x70, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x41, 0x70, 0x70, 0x56, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x52, 0x09, 0x61, 0x70, 0x70, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x22, 0x1b, 0x0a, 0x09,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x22, 0x0a, 0x10, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3f, 0x0a,
	0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x41, 0x6c, 0x6c, 0x41, 0x70, 0x70, 0x12,
	0x2d, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x61, 0x70, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x41, 0x70,
	0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x61, 0x70, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x0f,
	0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x70, 0x70, 0x22,
	0x1f, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x10,
	0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x75, 0x6d,
	0x22, 0x3d, 0x0a, 0x06, 0x41, 0x70, 0x70, 0x50, 0x6f, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70,
	0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49,
	0x64, 0x12, 0x1c, 0x0a, 0x0a, 0x61, 0x70, 0x70, 0x5f, 0x70, 0x6f, 0x64, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x61, 0x70, 0x70, 0x50, 0x6f, 0x64, 0x49, 0x64, 0x22,
	0x46, 0x0a, 0x09, 0x41, 0x70, 0x70, 0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x12, 0x15, 0x0a, 0x06,
	0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x61, 0x70,
	0x70, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x61, 0x70, 0x70, 0x5f, 0x6d, 0x69, 0x64, 0x64, 0x6c,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x61, 0x70, 0x70, 0x4d,
	0x69, 0x64, 0x64, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x46, 0x0a, 0x09, 0x41, 0x70, 0x70, 0x56, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x61,
	0x70, 0x70, 0x5f, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x61, 0x70, 0x70, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x49, 0x64, 0x22,
	0x9e, 0x01, 0x0a, 0x0b, 0x52, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x61, 0x70, 0x70,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x61, 0x70, 0x70, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x22, 0x4f, 0x0a, 0x15, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x41, 0x6c, 0x6c, 0x41,
	0x70, 0x70, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x36, 0x0a, 0x0b, 0x61, 0x70, 0x70,
	0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x61, 0x70, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x41, 0x70, 0x70, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x22, 0x1c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32,
	0xaf, 0x05, 0x0a, 0x08, 0x41, 0x70, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x32, 0x0a, 0x06,
	0x41, 0x64, 0x64, 0x41, 0x70, 0x70, 0x12, 0x12, 0x2e, 0x61, 0x70, 0x70, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x2e, 0x52, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x12, 0x2e, 0x61, 0x70, 0x70,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x3a, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x70, 0x70, 0x42, 0x79, 0x49,
	0x44, 0x12, 0x13, 0x2e, 0x61, 0x70, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x1a, 0x12, 0x2e, 0x61, 0x70, 0x70, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x09,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x12, 0x12, 0x2e, 0x61, 0x70, 0x70, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x12, 0x2e,
	0x61, 0x70, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x70, 0x70, 0x42,
	0x79, 0x49, 0x44, 0x12, 0x13, 0x2e, 0x61, 0x70, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x1a, 0x12, 0x2e, 0x61, 0x70, 0x70, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x2e, 0x52, 0x41, 0x70, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x43,
	0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x6c, 0x6c, 0x41, 0x70, 0x70, 0x73, 0x12, 0x17,
	0x2e, 0x61, 0x70, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x41, 0x6c, 0x6c, 0x41, 0x70, 0x70, 0x1a, 0x18, 0x2e, 0x61, 0x70, 0x70, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x41, 0x6c, 0x6c, 0x41, 0x70,
	0x70, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c,
	0x6c, 0x4e, 0x75, 0x6d, 0x12, 0x13, 0x2e, 0x61, 0x70, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x1a, 0x12, 0x2e, 0x61, 0x70, 0x70, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x3f, 0x0a, 0x0f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x4e,
	0x75, 0x6d, 0x12, 0x13, 0x2e, 0x61, 0x70, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x1a, 0x15, 0x2e, 0x61, 0x70, 0x70, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4e, 0x75, 0x6d, 0x22, 0x00,
	0x12, 0x37, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x56, 0x69, 0x65, 0x77, 0x4e, 0x75, 0x6d, 0x12, 0x13,
	0x2e, 0x61, 0x70, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x44, 0x1a, 0x12, 0x2e, 0x61, 0x70, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x0c, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x56, 0x69, 0x65, 0x77, 0x4e, 0x75, 0x6d, 0x12, 0x13, 0x2e, 0x61, 0x70, 0x70, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x1a, 0x15,
	0x2e, 0x61, 0x70, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x4e, 0x75, 0x6d, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x15, 0x2e, 0x61, 0x70, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x2e, 0x52, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x12, 0x2e, 0x61,
	0x70, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x4d, 0x0a, 0x13, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x6c, 0x6c, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x44, 0x12, 0x13, 0x2e, 0x61, 0x70, 0x70, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x1a, 0x1f,
	0x2e, 0x61, 0x70, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x41, 0x6c, 0x6c, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22,
	0x00, 0x42, 0x1b, 0x5a, 0x19, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x70,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x3b, 0x61, 0x70, 0x70, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_appStore_appStore_proto_rawDescOnce sync.Once
	file_proto_appStore_appStore_proto_rawDescData = file_proto_appStore_appStore_proto_rawDesc
)

func file_proto_appStore_appStore_proto_rawDescGZIP() []byte {
	file_proto_appStore_appStore_proto_rawDescOnce.Do(func() {
		file_proto_appStore_appStore_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_appStore_appStore_proto_rawDescData)
	})
	return file_proto_appStore_appStore_proto_rawDescData
}

var file_proto_appStore_appStore_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_appStore_appStore_proto_goTypes = []interface{}{
	(*RAppInfo)(nil),              // 0: appStore.RAppInfo
	(*RequestID)(nil),             // 1: appStore.RequestID
	(*RequestCommentID)(nil),      // 2: appStore.RequestCommentID
	(*ResponseAllApp)(nil),        // 3: appStore.ResponseAllApp
	(*RequestAllApp)(nil),         // 4: appStore.RequestAllApp
	(*ResponseNum)(nil),           // 5: appStore.ResponseNum
	(*AppPod)(nil),                // 6: appStore.AppPod
	(*AppMiddle)(nil),             // 7: appStore.AppMiddle
	(*AppVolume)(nil),             // 8: appStore.AppVolume
	(*RAppComment)(nil),           // 9: appStore.RAppComment
	(*ResponseAllAppComment)(nil), // 10: appStore.ResponseAllAppComment
	(*Response)(nil),              // 11: appStore.Response
}
var file_proto_appStore_appStore_proto_depIdxs = []int32{
	6,  // 0: appStore.RAppInfo.app_pod:type_name -> appStore.AppPod
	7,  // 1: appStore.RAppInfo.app_middle:type_name -> appStore.AppMiddle
	8,  // 2: appStore.RAppInfo.app_volume:type_name -> appStore.AppVolume
	0,  // 3: appStore.ResponseAllApp.app_info:type_name -> appStore.RAppInfo
	9,  // 4: appStore.ResponseAllAppComment.app_comment:type_name -> appStore.RAppComment
	0,  // 5: appStore.AppStore.AddApp:input_type -> appStore.RAppInfo
	1,  // 6: appStore.AppStore.DeleteAppByID:input_type -> appStore.RequestID
	0,  // 7: appStore.AppStore.UpdateApp:input_type -> appStore.RAppInfo
	1,  // 8: appStore.AppStore.QueryAppByID:input_type -> appStore.RequestID
	4,  // 9: appStore.AppStore.QueryAllApps:input_type -> appStore.RequestAllApp
	1,  // 10: appStore.AppStore.AddInstallNum:input_type -> appStore.RequestID
	1,  // 11: appStore.AppStore.QueryInstallNum:input_type -> appStore.RequestID
	1,  // 12: appStore.AppStore.AddViewNum:input_type -> appStore.RequestID
	1,  // 13: appStore.AppStore.QueryViewNum:input_type -> appStore.RequestID
	9,  // 14: appStore.AppStore.AddComment:input_type -> appStore.RAppComment
	1,  // 15: appStore.AppStore.QueryAllCommentByID:input_type -> appStore.RequestID
	11, // 16: appStore.AppStore.AddApp:output_type -> appStore.Response
	11, // 17: appStore.AppStore.DeleteAppByID:output_type -> appStore.Response
	11, // 18: appStore.AppStore.UpdateApp:output_type -> appStore.Response
	0,  // 19: appStore.AppStore.QueryAppByID:output_type -> appStore.RAppInfo
	3,  // 20: appStore.AppStore.QueryAllApps:output_type -> appStore.ResponseAllApp
	11, // 21: appStore.AppStore.AddInstallNum:output_type -> appStore.Response
	5,  // 22: appStore.AppStore.QueryInstallNum:output_type -> appStore.ResponseNum
	11, // 23: appStore.AppStore.AddViewNum:output_type -> appStore.Response
	5,  // 24: appStore.AppStore.QueryViewNum:output_type -> appStore.ResponseNum
	11, // 25: appStore.AppStore.AddComment:output_type -> appStore.Response
	10, // 26: appStore.AppStore.QueryAllCommentByID:output_type -> appStore.ResponseAllAppComment
	16, // [16:27] is the sub-list for method output_type
	5,  // [5:16] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_appStore_appStore_proto_init() }
func file_proto_appStore_appStore_proto_init() {
	if File_proto_appStore_appStore_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_appStore_appStore_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RAppInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_appStore_appStore_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_appStore_appStore_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestCommentID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_appStore_appStore_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseAllApp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_appStore_appStore_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestAllApp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_appStore_appStore_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseNum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_appStore_appStore_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppPod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_appStore_appStore_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppMiddle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_appStore_appStore_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppVolume); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_appStore_appStore_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RAppComment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_appStore_appStore_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseAllAppComment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_appStore_appStore_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_appStore_appStore_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_appStore_appStore_proto_goTypes,
		DependencyIndexes: file_proto_appStore_appStore_proto_depIdxs,
		MessageInfos:      file_proto_appStore_appStore_proto_msgTypes,
	}.Build()
	File_proto_appStore_appStore_proto = out.File
	file_proto_appStore_appStore_proto_rawDesc = nil
	file_proto_appStore_appStore_proto_goTypes = nil
	file_proto_appStore_appStore_proto_depIdxs = nil
}
