name: "go.micro.service.middleware"
service_Host: "127.0.0.1"
service_Port: "8081"
version: "latest"

consul:
  host: "127.0.0.1"
  port: 8500
  prefix: "/micro/config"
  path: "mysql"

tracer:
  host: "127.0.0.1"
  port: 6831



prometheus:
  port: 9192