FROM golang:alpine AS demoMiddleware

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

WORKDIR /go-paas/middleware

COPY go.mod .
COPY go.sum .
ENV GOPROXY https://goproxy.cn
RUN go mod download

COPY . .
RUN go build -o go-paas-middleware .

FROM scratch

COPY ./conf /conf

COPY --from=demoMiddleware /go-paas/middleware/go-paas-middleware /

EXPOSE 8089
ENTRYPOINT ["/go-paas-middleware", "conf/config.yaml"]