FROM golang:alpine AS demoAppStore

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

WORKDIR /go-paas/appStore

COPY go.mod .
COPY go.sum .
ENV GOPROXY https://goproxy.cn
RUN go mod download

COPY . .

RUN go build -o go-paas-appStore

FROM scratch

COPY ./conf /conf

COPY --from=demoAppStore /go-paas/appStore/go-paas-appStore /

EXPOSE 8091

ENTRYPOINT ["/go-paas-appStore", "conf/config.yaml"]