FROM golang:alpine AS demoUserApi
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

WORKDIR /go-paas/userApi

COPY go.mod .
COPY go.sum .
ENV GOPROXY https://goproxy.cn
RUN go mod download

COPY . .

RUN go build -o go-paas-userApi .

FROM scratch

COPY ./conf /conf

COPY --from=demoUserApi /go-paas/userApi/go-paas-userApi /

EXPOSE 8094

ENTRYPOINT ["/go-paas-userApi", "conf/config.yaml"]