// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.7
// source: proto/route/route.proto

package route

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RRouteInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RouteName      string       `protobuf:"bytes,2,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`
	RouteNamespace string       `protobuf:"bytes,3,opt,name=route_namespace,json=routeNamespace,proto3" json:"route_namespace,omitempty"`
	RouteHost      string       `protobuf:"bytes,4,opt,name=route_host,json=routeHost,proto3" json:"route_host,omitempty"`
	RoutePath      []*RoutePath `protobuf:"bytes,5,rep,name=route_path,json=routePath,proto3" json:"route_path,omitempty"`
}

func (x *RRouteInfo) Reset() {
	*x = RRouteInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_route_route_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RRouteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RRouteInfo) ProtoMessage() {}

func (x *RRouteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_route_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RRouteInfo.ProtoReflect.Descriptor instead.
func (*RRouteInfo) Descriptor() ([]byte, []int) {
	return file_proto_route_route_proto_rawDescGZIP(), []int{0}
}

func (x *RRouteInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RRouteInfo) GetRouteName() string {
	if x != nil {
		return x.RouteName
	}
	return ""
}

func (x *RRouteInfo) GetRouteNamespace() string {
	if x != nil {
		return x.RouteNamespace
	}
	return ""
}

func (x *RRouteInfo) GetRouteHost() string {
	if x != nil {
		return x.RouteHost
	}
	return ""
}

func (x *RRouteInfo) GetRoutePath() []*RoutePath {
	if x != nil {
		return x.RoutePath
	}
	return nil
}

type RoutePath struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                      int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RouteId                 int64  `protobuf:"varint,2,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	RoutePathName           string `protobuf:"bytes,3,opt,name=route_path_name,json=routePathName,proto3" json:"route_path_name,omitempty"`
	RouteBackendService     string `protobuf:"bytes,4,opt,name=route_backend_service,json=routeBackendService,proto3" json:"route_backend_service,omitempty"`
	RouteBackendServicePort int32  `protobuf:"varint,5,opt,name=route_backend_service_port,json=routeBackendServicePort,proto3" json:"route_backend_service_port,omitempty"`
}

func (x *RoutePath) Reset() {
	*x = RoutePath{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_route_route_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoutePath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutePath) ProtoMessage() {}

func (x *RoutePath) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_route_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutePath.ProtoReflect.Descriptor instead.
func (*RoutePath) Descriptor() ([]byte, []int) {
	return file_proto_route_route_proto_rawDescGZIP(), []int{1}
}

func (x *RoutePath) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoutePath) GetRouteId() int64 {
	if x != nil {
		return x.RouteId
	}
	return 0
}

func (x *RoutePath) GetRoutePathName() string {
	if x != nil {
		return x.RoutePathName
	}
	return ""
}

func (x *RoutePath) GetRouteBackendService() string {
	if x != nil {
		return x.RouteBackendService
	}
	return ""
}

func (x *RoutePath) GetRouteBackendServicePort() int32 {
	if x != nil {
		return x.RouteBackendServicePort
	}
	return 0
}

type RRouteID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RRouteID) Reset() {
	*x = RRouteID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_route_route_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RRouteID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RRouteID) ProtoMessage() {}

func (x *RRouteID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_route_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RRouteID.ProtoReflect.Descriptor instead.
func (*RRouteID) Descriptor() ([]byte, []int) {
	return file_proto_route_route_proto_rawDescGZIP(), []int{2}
}

func (x *RRouteID) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RequestQueryAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RequestQueryAll) Reset() {
	*x = RequestQueryAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_route_route_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestQueryAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestQueryAll) ProtoMessage() {}

func (x *RequestQueryAll) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_route_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestQueryAll.ProtoReflect.Descriptor instead.
func (*RequestQueryAll) Descriptor() ([]byte, []int) {
	return file_proto_route_route_proto_rawDescGZIP(), []int{3}
}

type ResponseInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ResponseInfo) Reset() {
	*x = ResponseInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_route_route_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseInfo) ProtoMessage() {}

func (x *ResponseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_route_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseInfo.ProtoReflect.Descriptor instead.
func (*ResponseInfo) Descriptor() ([]byte, []int) {
	return file_proto_route_route_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseInfo) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ResponseAllRoute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RouteInfo []*RRouteInfo `protobuf:"bytes,1,rep,name=route_info,json=routeInfo,proto3" json:"route_info,omitempty"`
}

func (x *ResponseAllRoute) Reset() {
	*x = ResponseAllRoute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_route_route_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseAllRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseAllRoute) ProtoMessage() {}

func (x *ResponseAllRoute) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_route_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseAllRoute.ProtoReflect.Descriptor instead.
func (*ResponseAllRoute) Descriptor() ([]byte, []int) {
	return file_proto_route_route_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseAllRoute) GetRouteInfo() []*RRouteInfo {
	if x != nil {
		return x.RouteInfo
	}
	return nil
}

var File_proto_route_route_proto protoreflect.FileDescriptor

var file_proto_route_route_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2f, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x22, 0xb4, 0x01, 0x0a, 0x0a, 0x52, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27,
	0x0a, 0x0f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x5f, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x0a, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x50, 0x61, 0x74, 0x68, 0x52, 0x09, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22, 0xcf, 0x01, 0x0a, 0x09, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x64,
	0x12, 0x26, 0x0a, 0x0f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x50, 0x61, 0x74, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x15, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x42, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x1a,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x17, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x1a, 0x0a, 0x08, 0x52, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x6c, 0x6c, 0x22, 0x20, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x44, 0x0a, 0x10, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x41, 0x6c, 0x6c, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x30,
	0x0a, 0x0a, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x52, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x32, 0xa9, 0x02, 0x0a, 0x05, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x34, 0x0a, 0x08, 0x41, 0x64,
	0x64, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x11, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x52,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x13, 0x2e, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00,
	0x12, 0x35, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12,
	0x0f, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x52, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x44,
	0x1a, 0x13, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x11, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x52,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x13, 0x2e, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00,
	0x12, 0x36, 0x0a, 0x0e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x42, 0x79,
	0x49, 0x44, 0x12, 0x0f, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x52, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x49, 0x44, 0x1a, 0x11, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x52, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x41, 0x6c, 0x6c, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x6c,
	0x6c, 0x1a, 0x17, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x41, 0x6c, 0x6c, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x3b, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_route_route_proto_rawDescOnce sync.Once
	file_proto_route_route_proto_rawDescData = file_proto_route_route_proto_rawDesc
)

func file_proto_route_route_proto_rawDescGZIP() []byte {
	file_proto_route_route_proto_rawDescOnce.Do(func() {
		file_proto_route_route_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_route_route_proto_rawDescData)
	})
	return file_proto_route_route_proto_rawDescData
}

var file_proto_route_route_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_route_route_proto_goTypes = []interface{}{
	(*RRouteInfo)(nil),       // 0: route.RRouteInfo
	(*RoutePath)(nil),        // 1: route.RoutePath
	(*RRouteID)(nil),         // 2: route.RRouteID
	(*RequestQueryAll)(nil),  // 3: route.RequestQueryAll
	(*ResponseInfo)(nil),     // 4: route.ResponseInfo
	(*ResponseAllRoute)(nil), // 5: route.ResponseAllRoute
}
var file_proto_route_route_proto_depIdxs = []int32{
	1, // 0: route.RRouteInfo.route_path:type_name -> route.RoutePath
	0, // 1: route.ResponseAllRoute.route_info:type_name -> route.RRouteInfo
	0, // 2: route.Route.AddRoute:input_type -> route.RRouteInfo
	2, // 3: route.Route.DeleteRoute:input_type -> route.RRouteID
	0, // 4: route.Route.UpdateRoute:input_type -> route.RRouteInfo
	2, // 5: route.Route.QueryRouteByID:input_type -> route.RRouteID
	3, // 6: route.Route.QueryAllRoute:input_type -> route.RequestQueryAll
	4, // 7: route.Route.AddRoute:output_type -> route.ResponseInfo
	4, // 8: route.Route.DeleteRoute:output_type -> route.ResponseInfo
	4, // 9: route.Route.UpdateRoute:output_type -> route.ResponseInfo
	0, // 10: route.Route.QueryRouteByID:output_type -> route.RRouteInfo
	5, // 11: route.Route.QueryAllRoute:output_type -> route.ResponseAllRoute
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_route_route_proto_init() }
func file_proto_route_route_proto_init() {
	if File_proto_route_route_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_route_route_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RRouteInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_route_route_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoutePath); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_route_route_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RRouteID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_route_route_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestQueryAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_route_route_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_route_route_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseAllRoute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_route_route_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_route_route_proto_goTypes,
		DependencyIndexes: file_proto_route_route_proto_depIdxs,
		MessageInfos:      file_proto_route_route_proto_msgTypes,
	}.Build()
	File_proto_route_route_proto = out.File
	file_proto_route_route_proto_rawDesc = nil
	file_proto_route_route_proto_goTypes = nil
	file_proto_route_route_proto_depIdxs = nil
}
