FROM golang:alpine AS demoRoute
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

WORKDIR /go-paas/route

COPY go.mod .
COPY go.sum .
ENV GOPROXY https://goproxy.cn
RUN go mod download

COPY . .

RUN go build -o go-paas-route

FROM scratch

COPY ./conf /conf

COPY --from=demoRoute /go-paas/route/go-paas-route /

EXPOSE 8085
ENTRYPOINT ["/go-paas-route", "conf/config.yaml"]