// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/appStoreApi/appStoreApi.proto

package appStoreApi

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for AppStoreApi service

func NewAppStoreApiEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for AppStoreApi service

type AppStoreApiService interface {
	AddApp(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	DeleteAppByID(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	UpdateApp(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	QueryAppByID(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	QueryAllApps(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	AddInstallNum(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	QueryInstallNum(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	AddViewNum(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	QueryViewNum(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	AddComment(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	//  rpc DeleteComment(RequestCommentID)  returns(Response) {}
	QueryAllCommentByID(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type appStoreApiService struct {
	c    client.Client
	name string
}

func NewAppStoreApiService(name string, c client.Client) AppStoreApiService {
	return &appStoreApiService{
		c:    c,
		name: name,
	}
}

func (c *appStoreApiService) AddApp(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "AppStoreApi.AddApp", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appStoreApiService) DeleteAppByID(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "AppStoreApi.DeleteAppByID", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appStoreApiService) UpdateApp(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "AppStoreApi.UpdateApp", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appStoreApiService) QueryAppByID(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "AppStoreApi.QueryAppByID", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appStoreApiService) QueryAllApps(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "AppStoreApi.QueryAllApps", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appStoreApiService) AddInstallNum(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "AppStoreApi.AddInstallNum", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appStoreApiService) QueryInstallNum(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "AppStoreApi.QueryInstallNum", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appStoreApiService) AddViewNum(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "AppStoreApi.AddViewNum", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appStoreApiService) QueryViewNum(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "AppStoreApi.QueryViewNum", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appStoreApiService) AddComment(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "AppStoreApi.AddComment", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appStoreApiService) QueryAllCommentByID(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "AppStoreApi.QueryAllCommentByID", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AppStoreApi service

type AppStoreApiHandler interface {
	AddApp(context.Context, *Request, *Response) error
	DeleteAppByID(context.Context, *Request, *Response) error
	UpdateApp(context.Context, *Request, *Response) error
	QueryAppByID(context.Context, *Request, *Response) error
	QueryAllApps(context.Context, *Request, *Response) error
	AddInstallNum(context.Context, *Request, *Response) error
	QueryInstallNum(context.Context, *Request, *Response) error
	AddViewNum(context.Context, *Request, *Response) error
	QueryViewNum(context.Context, *Request, *Response) error
	AddComment(context.Context, *Request, *Response) error
	//  rpc DeleteComment(RequestCommentID)  returns(Response) {}
	QueryAllCommentByID(context.Context, *Request, *Response) error
}

func RegisterAppStoreApiHandler(s server.Server, hdlr AppStoreApiHandler, opts ...server.HandlerOption) error {
	type appStoreApi interface {
		AddApp(ctx context.Context, in *Request, out *Response) error
		DeleteAppByID(ctx context.Context, in *Request, out *Response) error
		UpdateApp(ctx context.Context, in *Request, out *Response) error
		QueryAppByID(ctx context.Context, in *Request, out *Response) error
		QueryAllApps(ctx context.Context, in *Request, out *Response) error
		AddInstallNum(ctx context.Context, in *Request, out *Response) error
		QueryInstallNum(ctx context.Context, in *Request, out *Response) error
		AddViewNum(ctx context.Context, in *Request, out *Response) error
		QueryViewNum(ctx context.Context, in *Request, out *Response) error
		AddComment(ctx context.Context, in *Request, out *Response) error
		QueryAllCommentByID(ctx context.Context, in *Request, out *Response) error
	}
	type AppStoreApi struct {
		appStoreApi
	}
	h := &appStoreApiHandler{hdlr}
	return s.Handle(s.NewHandler(&AppStoreApi{h}, opts...))
}

type appStoreApiHandler struct {
	AppStoreApiHandler
}

func (h *appStoreApiHandler) AddApp(ctx context.Context, in *Request, out *Response) error {
	return h.AppStoreApiHandler.AddApp(ctx, in, out)
}

func (h *appStoreApiHandler) DeleteAppByID(ctx context.Context, in *Request, out *Response) error {
	return h.AppStoreApiHandler.DeleteAppByID(ctx, in, out)
}

func (h *appStoreApiHandler) UpdateApp(ctx context.Context, in *Request, out *Response) error {
	return h.AppStoreApiHandler.UpdateApp(ctx, in, out)
}

func (h *appStoreApiHandler) QueryAppByID(ctx context.Context, in *Request, out *Response) error {
	return h.AppStoreApiHandler.QueryAppByID(ctx, in, out)
}

func (h *appStoreApiHandler) QueryAllApps(ctx context.Context, in *Request, out *Response) error {
	return h.AppStoreApiHandler.QueryAllApps(ctx, in, out)
}

func (h *appStoreApiHandler) AddInstallNum(ctx context.Context, in *Request, out *Response) error {
	return h.AppStoreApiHandler.AddInstallNum(ctx, in, out)
}

func (h *appStoreApiHandler) QueryInstallNum(ctx context.Context, in *Request, out *Response) error {
	return h.AppStoreApiHandler.QueryInstallNum(ctx, in, out)
}

func (h *appStoreApiHandler) AddViewNum(ctx context.Context, in *Request, out *Response) error {
	return h.AppStoreApiHandler.AddViewNum(ctx, in, out)
}

func (h *appStoreApiHandler) QueryViewNum(ctx context.Context, in *Request, out *Response) error {
	return h.AppStoreApiHandler.QueryViewNum(ctx, in, out)
}

func (h *appStoreApiHandler) AddComment(ctx context.Context, in *Request, out *Response) error {
	return h.AppStoreApiHandler.AddComment(ctx, in, out)
}

func (h *appStoreApiHandler) QueryAllCommentByID(ctx context.Context, in *Request, out *Response) error {
	return h.AppStoreApiHandler.QueryAllCommentByID(ctx, in, out)
}
